

CC = g++



CFLAGS = -c -Wall -fexceptions

all:run


Fabrica.o: Fabrica.cpp
	$(CC) $(CFLAGS)  -c Fabrica.cpp -o Fabrica.o

HandlerUsuario.o: HandlerUsuario.cpp
	$(CC) $(CFLAGS)  -c HandlerUsuario.cpp -o HandlerUsuario.o

HandlerMensaje.o: HandlerMensaje.cpp
	$(CC) $(CFLAGS)  -c HandlerMensaje.cpp -o HandlerMensaje.o

HandlerAsignatura.o: HandlerAsignatura.cpp
	$(CC) $(CFLAGS)  -c HandlerAsignatura.cpp -o HandlerAsignatura.o

Imprimir.o: Imprimir.cpp
	$(CC) $(CFLAGS)  -c Imprimir.cpp -o Imprimir.o

Estudiante.o: Estudiante.cpp
	$(CC) $(CFLAGS)  -c Estudiante.cpp -o Estudiante.o

EliminarSet.o: EliminarSet.cpp
	$(CC) $(CFLAGS)  -c EliminarSet.cpp -o EliminarSet.o

DtUsuario.o: DtUsuario.cpp
	$(CC) $(CFLAGS)  -c DtUsuario.cpp -o DtUsuario.o

DtTiempoAsignatura.o: DtTiempoAsignatura.cpp
	$(CC) $(CFLAGS)  -c DtTiempoAsignatura.cpp -o DtTiempoAsignatura.o

DtTeorico.o: DtTeorico.cpp
	$(CC) $(CFLAGS)  -c DtTeorico.cpp -o DtTeorico.o

Usuario.o: Usuario.cpp
	$(CC) $(CFLAGS)  -c Usuario.cpp -o Usuario.o

Teorico.o: Teorico.cpp
	$(CC) $(CFLAGS)  -c Teorico.cpp -o Teorico.o

Respuesta.o: Respuesta.cpp
	$(CC) $(CFLAGS)  -c Respuesta.cpp -o Respuesta.o

Reloj.o: Reloj.cpp
	$(CC) $(CFLAGS)  -c Reloj.cpp -o Reloj.o

Practico.o: Practico.cpp
	$(CC) $(CFLAGS)  -c Practico.cpp -o Practico.o

Monitoreo.o: Monitoreo.cpp
	$(CC) $(CFLAGS)  -c Monitoreo.cpp -o Monitoreo.o

Menu.o: Menu.cpp
	$(CC) $(CFLAGS)  -c Menu.cpp -o Menu.o

main.o: main.cpp
	$(CC) $(CFLAGS)  -c main.cpp -o main.o
	
Mensaje.o: Mensaje.cpp
	$(CC) $(CFLAGS)  -c Mensaje.cpp -o Mensaje.o

InfoVisita.o: InfoVisita.cpp
	$(CC) $(CFLAGS)  -c InfoVisita.cpp -o InfoVisita.o

DtEstudiante.o: DtEstudiante.cpp
	$(CC) $(CFLAGS)  -c DtEstudiante.cpp -o DtEstudiante.o

DtDocente.o: DtDocente.cpp
	$(CC) $(CFLAGS)  -c DtDocente.cpp -o DtDocente.o

DtClase2.o: DtClase2.cpp
	$(CC) $(CFLAGS)  -c DtClase2.cpp -o DtClase2.o

DtClase.o: DtClase.cpp
	$(CC) $(CFLAGS)  -c DtClase.cpp -o DtClase.o

DtAsignatura.o: DtAsignatura.cpp
	$(CC) $(CFLAGS)  -c DtAsignatura.cpp -o DtAsignatura.o

Docente.o: Docente.cpp
	$(CC) $(CFLAGS)  -c Docente.cpp -o Docente.o

ControladorUsuario.o: ControladorUsuario.cpp
	$(CC) $(CFLAGS)  -c ControladorUsuario.cpp -o ControladorUsuario.o

ControladorClase.o: ControladorClase.cpp
	$(CC) $(CFLAGS)  -c ControladorClase.cpp -o ControladorClase.o

ControladorAsignatura.o: ControladorAsignatura.cpp
	$(CC) $(CFLAGS)  -c ControladorAsignatura.cpp -o ControladorAsignatura.o

Clase.o: Clase.cpp
	$(CC) $(CFLAGS)  -c Clase.cpp -o Clase.o

Asignatura.o: Asignatura.cpp
	$(CC) $(CFLAGS)  -c Asignatura.cpp -o Asignatura.o

DtMonitoreo.o: DtMonitoreo.cpp
	$(CC) $(CFLAGS)  -c DtMonitoreo.cpp -o DtMonitoreo.o

DtReloj.o: DtReloj.cpp
	$(CC) $(CFLAGS)  -c DtReloj.cpp -o DtReloj.o

DtPromedioClase.o: DtPromedioClase.cpp
	$(CC) $(CFLAGS)  -c DtPromedioClase.cpp -o DtPromedioClase.o

DtPractico.o: DtPractico.cpp
	$(CC) $(CFLAGS)  -c DtPractico.cpp -o DtPractico.o

DtNotificacion.o: DtNotificacion.cpp
	$(CC) $(CFLAGS)  -c DtNotificacion.cpp -o DtNotificacion.o

DtNombreClase.o: DtNombreClase.cpp
	$(CC) $(CFLAGS)  -c DtNombreClase.cpp -o DtNombreClase.o

Asignacion.o: Asignacion.cpp
	$(CC) $(CFLAGS)  -c Asignacion.cpp -o Asignacion.o

DtMensaje.o: DtMensaje.cpp
	$(CC) $(CFLAGS)  -c DtMensaje.cpp -o DtMensaje.o

DtInfoEstudiante.o: DtInfoEstudiante.cpp
	$(CC) $(CFLAGS)  -c DtInfoEstudiante.cpp -o DtInfoEstudiante.o

DtInfo.o: DtInfo.cpp
	$(CC) $(CFLAGS)  -c DtInfo.cpp -o DtInfo.o

DtHora.o: DtHora.cpp
	$(CC) $(CFLAGS)  -c DtHora.cpp -o DtHora.o

DtFecha.o: DtFecha.cpp
	$(CC) $(CFLAGS)  -c DtFecha.cpp -o DtFecha.o

	
main: Fabrica.o HandlerUsuario.o HandlerMensaje.o HandlerAsignatura.o Imprimir.o Estudiante.o EliminarSet.o DtUsuario.o DtTiempoAsignatura.o DtTeorico.o main.o Usuario.o Teorico.o Respuesta.o Reloj.o Practico.o Monitoreo.o Menu.o Mensaje.o InfoVisita.o DtEstudiante.o DtDocente.o DtClase2.o DtClase.o DtAsignatura.o Docente.o ControladorUsuario.o ControladorClase.o ControladorAsignatura.o Clase.o Asignatura.o DtMonitoreo.o DtReloj.o DtPromedioClase.o DtPractico.o DtNotificacion.o DtNombreClase.o Asignacion.o DtMensaje.o DtInfoEstudiante.o DtInfo.o DtHora.o DtFecha.o	
	$(CC) Fabrica.o HandlerUsuario.o HandlerMensaje.o HandlerAsignatura.o Imprimir.o Estudiante.o EliminarSet.o DtUsuario.o DtTiempoAsignatura.o DtTeorico.o main.o Usuario.o Teorico.o Respuesta.o Reloj.o Practico.o Monitoreo.o Menu.o Mensaje.o InfoVisita.o DtEstudiante.o DtDocente.o DtClase2.o DtClase.o DtAsignatura.o Docente.o ControladorUsuario.o ControladorClase.o ControladorAsignatura.o Clase.o Asignatura.o DtMonitoreo.o DtReloj.o DtPromedioClase.o DtPractico.o DtNotificacion.o DtNombreClase.o Asignacion.o DtMensaje.o DtInfoEstudiante.o DtInfo.o DtHora.o DtFecha.o -o main
	
	
	
run: main
	./main
	
clean: 
	rm *o main
